version: "3"
services:
  api:
    container_name: nodeapp
    image: api-node-challenge
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - survey-network

  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27017:27017"  
    command: "mongod --quiet --logpath /dev/null" 
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: survey
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: survey
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    networks:
      - survey-network
secrets:
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
  mongodb_root_username:
    file: ./secrets/mongodb_root_username.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt
  mongodb_username:
    file: ./secrets/mongodb_username.txt

networks:
  survey-network:

